[package]
name = "ctf-pwn"
version = "0.1.0"
edition = "2021"
authors = ["Jovan Pavlovic"]
description = "Pwn utilities for Rust."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
