[package]
name = "ctf-pwn"
version = "0.1.0"
edition = "2021"
authors = ["Jovan Pavlovic"]
description = "Pwn utilities for Rust."
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ascii = "1.1.0"
bytes = "1.4.0"
duct = "0.13.6"
futures-util = "0.3.28"
paste = "1.0.14"
thiserror = "1.0.47"
tokio = { version = "1.32.0", features = ["full"] }
